---
#################################################################
# Create wireguard server

- name: Deploy wireguard
  hosts: wireguard
  remote_user: ec2-user
  gather_facts: no
  become: yes

  tasks:

    - name: Install wireguard
      include_role:
        name: roles/wireguard