---
- name: "Create inventory"
  hosts: localhost
  connection: local
  become: false
  gather_facts: no

  tasks:

    - name: Adding hosts to inventory group 'wireguard'
      add_host:
        hostname: "{{ endpoint }}"
        groups: "wireguard"

#################################################################
# Create wireguard server

- name: Deploy wireguard
  hosts: wireguard
  remote_user: ec2-user
  gather_facts: no
  become: yes

  tasks:
      
    - name: Install wireguard
      include_role:
        name: roles/wireguard

    - name: Add dns update components
      include_role:
        name: roles/route53update        